package com.example.hibernate.model;
// Generated 27 ene 2026, 17:26:14 by Hibernate Tools 6.6.4.Final


import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name="modulo"
)
public class Modulo  implements java.io.Serializable {


     private Integer idModulo;
     private String nombre;
     private Set<Profesor> profesores = new HashSet<Profesor>(0);

    public Modulo() {
    }

	
    public Modulo(String nombre) {
        this.nombre = nombre;
    }
    public Modulo(String nombre, Set<Profesor> profesors) {
       this.nombre = nombre;
       this.profesores = profesors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idModulo", unique=true, nullable=false)
    public Integer getIdModulo() {
        return this.idModulo;
    }
    
    public void setIdModulo(Integer idModulo) {
        this.idModulo = idModulo;
    }

    
    @Column(name="nombre", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy = "modulos")
   
    public Set<Profesor> getProfesores() {
        return this.profesores;
    }
    
    public void setProfesores(Set<Profesor> profesors) {
        this.profesores = profesors;
    }




}


