package com.example.hibernate.model;
// Generated 27 ene 2026, 17:26:14 by Hibernate Tools 6.6.4.Final


import static jakarta.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Profesor generated by hbm2java
 */
@Entity
@Table(name="profesor"
)
@NamedQuery(
    name = "Profesor_findByNombreApe1Ape2",
    query = "SELECT p FROM Profesor p " +
            "WHERE p.nombre = :nombre " +
            "AND p.ape1 = :apellido1 " +
            "AND p.ape2 = :apellido2"
)
public class Profesor  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String ape1;
     private String ape2;
     private String tipoFuncionario;
     private Set<ContactInfo> contactinfos = new HashSet<ContactInfo>(0);
     private Set<Modulo> modulos = new HashSet<Modulo>(0);

    public Profesor() {
    }

	
    public Profesor(String nombre, String ape1, String ape2) {
        this.nombre = nombre;
        this.ape1 = ape1;
        this.ape2 = ape2;
    }
    public Profesor(String nombre, String ape1, String ape2, String tipoFuncionario, Set<ContactInfo> contactinfos, Set<Modulo> modulos) {
       this.nombre = nombre;
       this.ape1 = ape1;
       this.ape2 = ape2;
       this.tipoFuncionario = tipoFuncionario;
       this.contactinfos = contactinfos;
       this.modulos = modulos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=255)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="ape1", nullable=false, length=255)
    public String getApe1() {
        return this.ape1;
    }
    
    public void setApe1(String ape1) {
        this.ape1 = ape1;
    }

    
    @Column(name="ape2", nullable=false, length=255)
    public String getApe2() {
        return this.ape2;
    }
    
    public void setApe2(String ape2) {
        this.ape2 = ape2;
    }

    
    @Column(name="tipoFuncionario", length=100)
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="profesor")
    public Set<ContactInfo> getContactinfos() {
        return this.contactinfos;
    }
    
    public void setContactinfos(Set<ContactInfo> contactinfos) {
        this.contactinfos = contactinfos;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="profesormodulo", catalog="instituto", joinColumns = { 
        @JoinColumn(name="idProfesor", nullable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idModulo", nullable=false) })
    public Set<Modulo> getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set<Modulo> modulos) {
        this.modulos = modulos;
    }




public void addModulo(Modulo mod) {

getModulos().add(mod);

//conviene  usar getModulos() en lugar de this.modulos para forzar las inicializaciones de los objetos proxy en caso de inicialización //lazy

mod.getProfesors().add(this);

}


}


